- name: install monitoring stack
  hosts: monitor
  become: yes
  roles:
  - prometheus
  - grafana
- name: install node-exporter
  hosts: all
  become: yes
  roles:
  - node-exporter

#ansible-playbook -i 00inventory.yaml playbook.yml